name: mobile_app_ar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  supabase: ^0.2.3
  supabase_flutter: ^0.2.3
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.6
  image_picker: ^0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets: 
    - lib/assets/logo_final.png
    - lib/assets/Ph_flag.svg
  uses-material-design: true
